version: "3.7"

services:
  pgi:
    image: &pgi pgi
    build:
      context: .
      dockerfile: ./ci/Dockerfile
    volumes:
      - .:/libsrc/pgi
    # command: sh -c "sleep 5 && sudo mkdir -p build && cd build && sudo cmake .. && sudo make && sudo ./main"

  postgres_image:
    build:
      context: .
      dockerfile: ./ci/Dockerfile.db
    env_file:
      - ci/.env
