connection:
  host: postgres_image 
  port: 5432
  dbname: postgres 
  user: postgres 
  password: mainpassword 
  connect_timeout: 10

tables:
  - public.test_table
  - public.test_table2
  - public.test_table3


field_length_mapping:
  timestamptz: 26
  timestamp: 23
  float8: 5
  int2: 5
  int8: 5 
  varchar: 12

