version: "3.7"

services:
  pgi_test:
    build:
      context: ./..
      dockerfile: ./ci/Dockerfile
    command: sh -c "sleep 5 && ls &&  cd example && sudo mkdir -p build && cd build && sudo cmake .. && sudo make && sudo ./main"
    working_dir: /libsrc/pgi

  postgres_image:
    build:
      context: ./..
      dockerfile: ./ci/Dockerfile.db
    env_file:
      - .env
